@extends('layouts.app')

@section('content')
<div class="space-y-6">
    <div class="space-y-2">
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
            Advisory Board
        </span>
        <h3 class="text-2xl sm:text-3xl font-extrabold text-white">Expert Advisory & Logs</h3>
        <p class="text-sm text-slate-400">Ask customized questions to our AI agronomist and view verified resolutions.</p>
    </div>

    @if(session('success'))
        <div class="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold leading-normal">
            {{ session('success') }}
        </div>
    @endif

    <section id="advisor-sec" class="grid grid-cols-1 lg:grid-cols-12 gap-8 scroll-mt-20">
        <!-- Inquiry Form -->
        <div class="lg:col-span-5 glass-card rounded-2xl p-6 space-y-6 self-start">
            <div class="space-y-1">
                <h3 class="text-xl font-bold text-white">Ask an Agricultural Expert</h3>
                <p class="text-xs text-slate-400">Submit symptoms of crop stress, disease queries, or soil health questions below.</p>
            </div>

            <form action="{{ route('advisor.query') }}" method="POST" class="space-y-4">
                @csrf
                <div class="space-y-1.5">
                    <label for="farmer_name" class="text-xs font-semibold text-slate-300 block">Your Name</label>
                    <input type="text" name="farmer_name" id="farmer_name" required placeholder="Enter your name" value="{{ auth()->user()->name }}" class="input-premium w-full px-3 py-2.5 rounded-lg text-slate-200 text-sm">
                    @error('farmer_name')
                        <p class="text-rose-505 text-[11px] mt-1">{{ $message }}</p>
                    @enderror
                </div>

                <div class="space-y-1.5">
                    <label for="contact_number" class="text-xs font-semibold text-slate-300 block">Contact Number</label>
                    <input type="text" name="contact_number" id="contact_number" required placeholder="e.g. +91 9876543210" value="{{ old('contact_number') }}" class="input-premium w-full px-3 py-2.5 rounded-lg text-slate-200 text-sm">
                    @error('contact_number')
                        <p class="text-rose-505 text-[11px] mt-1">{{ $message }}</p>
                    @enderror
                </div>

                <div class="space-y-1.5">
                    <label for="crop_name" class="text-xs font-semibold text-slate-300 block">Crop Name (Optional)</label>
                    <select name="crop_name" id="crop_name" class="input-premium w-full px-3 py-2.5 rounded-lg text-slate-300 text-sm">
                        <option value="">-- General Agriculture Query --</option>
                        @foreach($crops as $c)
                            <option value="{{ $c->name }}" {{ old('crop_name') == $c->name ? 'selected' : '' }}>{{ $c->name }}</option>
                        @endforeach
                    </select>
                    @error('crop_name')
                        <p class="text-rose-505 text-[11px] mt-1">{{ $message }}</p>
                    @enderror
                </div>

                <div class="space-y-1.5">
                    <label for="query_text" class="text-xs font-semibold text-slate-300 block">Describe Your Problem / Question</label>
                    <textarea name="query_text" id="query_text" rows="4" required placeholder="Describe symptoms, soil appearance, or fertilizer concerns (minimum 10 characters)..." class="input-premium w-full px-3 py-2.5 rounded-lg text-slate-200 text-sm resize-none">{{ old('query_text') }}</textarea>
                    @error('query_text')
                        <p class="text-rose-505 text-[11px] mt-1">{{ $message }}</p>
                    @enderror
                </div>

                <button type="submit" class="w-full btn-premium-gradient py-3 rounded-lg text-xs font-bold uppercase tracking-wider mt-2">
                    Submit Advisory Request
                </button>
            </form>
        </div>

        <!-- Query Board Logs -->
        <div class="lg:col-span-7 space-y-5">
            <div class="space-y-1">
                <h3 class="text-xl font-bold text-white">Live Query Advisor Log</h3>
                <p class="text-xs text-slate-400">View advisory requests submitted by other farmers and responses generated by agricultural officers.</p>
            </div>

            <div class="space-y-4 max-h-[580px] overflow-y-auto pr-2" id="query-log-container">
                @forelse($queries as $query)
                    <div class="glass-card rounded-2xl p-5 border border-slate-900 space-y-4">
                        <div class="flex items-start justify-between">
                            <div class="space-y-0.5">
                                <span class="text-sm font-bold text-white">{{ $query->farmer_name }}</span>
                                <div class="flex items-center space-x-2 text-[10px] text-slate-500 font-medium">
                                    <span>Crop: {{ $query->crop_name }}</span>
                                    <span>•</span>
                                    <span>{{ $query->created_at->diffForHumans() }}</span>
                                </div>
                            </div>
                            <span class="px-2.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-emerald-500/10 text-emerald-450 border border-emerald-500/20">
                                {{ $query->status }}
                            </span>
                        </div>

                        <div class="text-xs text-slate-300 bg-slate-900/40 p-3 rounded-xl border border-slate-900 leading-relaxed font-sans">
                            <strong>Q:</strong> {{ $query->query_text }}
                        </div>

                        @if($query->response_text)
                            <div class="text-xs text-emerald-450/90 bg-emerald-500/[0.02] p-4 rounded-xl border border-emerald-500/10 leading-relaxed space-y-1 font-mono whitespace-pre-line">
                                <strong>Expert Advice:</strong>
                                {{ $query->response_text }}
                            </div>
                        @endif
                    </div>
                @empty
                    <div class="text-center py-12 glass-card rounded-2xl border border-slate-900">
                        <svg class="w-12 h-12 text-slate-600 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/></svg>
                        <p class="text-slate-400 font-medium">No inquiries posted yet. Be the first to ask!</p>
                    </div>
                @endforelse
            </div>
        </div>
    </section>
</div>
@endsection
